# Configuración del Simulador IoT Escalado
# Configuración para simular 100 sensores distribuidos

# Configuración general
simulation:
  total_sensors: 100
  zones: 10
  sensors_per_zone: 10
  duration_hours: 24  # Duración de la simulación (0 = infinita)
  
# Configuración del backend
backend:
  url: "http://127.0.0.1:8000"
  timeout: 10
  retry_attempts: 3
  retry_delay: 5

# Configuración de sensores
sensors:
  # Tipos de sensores disponibles
  types:
    - "temperature_humidity"
    - "temperature_only"
    - "humidity_only"
    - "soil_moisture"
    - "light_sensor"
  
  # Configuración por defecto
  default:
    reading_interval_min: 20  # segundos
    reading_interval_max: 60  # segundos
    failure_probability: 0.005  # 0.5% por lectura
    recovery_time_min: 300  # 5 minutos
    recovery_time_max: 1800  # 30 minutos
    reading_quality_min: 0.8
    reading_quality_max: 1.0

# Configuración de zonas
zones:
  # Coordenadas de diferentes regiones de España
  locations:
    - name: "Zona Norte"
      lat: 43.2
      lon: -2.9
      temp_base: 12.0
      humidity_base: 75.0
      temp_variance: 2.0
      humidity_variance: 5.0
      
    - name: "Zona Centro"
      lat: 40.4
      lon: -3.7
      temp_base: 15.0
      humidity_base: 60.0
      temp_variance: 2.5
      humidity_variance: 4.0
      
    - name: "Zona Este"
      lat: 39.5
      lon: -0.4
      temp_base: 18.0
      humidity_base: 65.0
      temp_variance: 2.0
      humidity_variance: 4.5
      
    - name: "Zona Sur"
      lat: 37.4
      lon: -5.9
      temp_base: 20.0
      humidity_base: 55.0
      temp_variance: 3.0
      humidity_variance: 3.0
      
    - name: "Zona Oeste"
      lat: 38.7
      lon: -9.1
      temp_base: 16.0
      humidity_base: 70.0
      temp_variance: 2.2
      humidity_variance: 4.8
      
    - name: "Zona Montaña"
      lat: 42.6
      lon: -1.6
      temp_base: 10.0
      humidity_base: 80.0
      temp_variance: 1.5
      humidity_variance: 6.0
      
    - name: "Zona Costera"
      lat: 36.7
      lon: -4.4
      temp_base: 19.0
      humidity_base: 70.0
      temp_variance: 2.8
      humidity_variance: 4.2
      
    - name: "Zona Interior"
      lat: 41.6
      lon: -4.7
      temp_base: 14.0
      humidity_base: 65.0
      temp_variance: 2.3
      humidity_variance: 4.5
      
    - name: "Zona Mediterránea"
      lat: 38.0
      lon: 1.1
      temp_base: 17.0
      humidity_base: 60.0
      temp_variance: 2.1
      humidity_variance: 4.0
      
    - name: "Zona Atlántica"
      lat: 43.5
      lon: -8.2
      temp_base: 13.0
      humidity_base: 75.0
      temp_variance: 1.8
      humidity_variance: 5.5

# Patrones de comportamiento
patterns:
  # Ciclo diario
  daily_cycle:
    temperature:
      min_hour: 6    # Hora de temperatura mínima
      max_hour: 14   # Hora de temperatura máxima
      amplitude: 8.0 # Amplitud de variación diaria
    humidity:
      min_hour: 14   # Hora de humedad mínima
      max_hour: 6    # Hora de humedad máxima
      amplitude: 20.0 # Amplitud de variación diaria
  
  # Efectos meteorológicos
  weather_effects:
    sunny:
      probability: 0.4
      temp_modifier: 1.2
      humidity_modifier: 0.8
    cloudy:
      probability: 0.3
      temp_modifier: 0.9
      humidity_modifier: 1.1
    rainy:
      probability: 0.2
      temp_modifier: 0.8
      humidity_modifier: 1.3
    stormy:
      probability: 0.1
      temp_modifier: 0.7
      humidity_modifier: 1.5
  
  # Efectos estacionales
  seasonal_effects:
    spring:
      months: [3, 4, 5]
      temp_modifier: 1.0
      humidity_modifier: 1.1
    summer:
      months: [6, 7, 8]
      temp_modifier: 1.3
      humidity_modifier: 0.9
    autumn:
      months: [9, 10, 11]
      temp_modifier: 0.9
      humidity_modifier: 1.2
    winter:
      months: [12, 1, 2]
      temp_modifier: 0.7
      humidity_modifier: 1.0

# Configuración de umbrales y alertas
thresholds:
  temperature:
    min: -10.0
    max: 50.0
    critical_low: 0.0
    critical_high: 40.0
  humidity:
    min: 10.0
    max: 100.0
    critical_low: 20.0
    critical_high: 90.0

# Configuración de logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "simulator.log"
  max_size_mb: 10
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Configuración de estadísticas
statistics:
  print_interval: 60  # segundos
  save_interval: 300  # segundos
  output_file: "simulation_stats.json"
  
# Configuración de monitoreo
monitoring:
  enable_web_interface: true
  web_port: 8080
  metrics_endpoint: "/metrics"
  health_check_interval: 30  # segundos
